Setting up repo
hmrc/excise-movement-control-system-api-tis pull request #2
Opened 2023-09-01 15:43 UTC by mauro-fanton

2023-09-05 15:31 UTC, mpbostock approved these changes

2023-09-05 15:32 UTC, mpbostock requested changes
There are some Typos "Sustem" should be "System"

2023-09-05 16:45 UTC, mauro-fanton commented
Yes, this is a wip. we will need to go trough it and changes all this reference. I have put some note on the ticket.

2023-09-06 09:08 UTC, ChrisCookOC commented
Generally we have used excise-movement-control-system-tis in a few places instead of excise-movement-control-system-api-tis. Is this intentional / does it matter?

2023-09-06 09:13 UTC, ChrisCookOC commented on source/documentation/partials/_BR003.md
> +   - if the type of origin is tax warehouse,ooptionally, validity of the link (manages or uses) between consignor and place of dispatch
"ooptionally" typo

2023-09-06 09:14 UTC, ChrisCookOC commented on source/documentation/partials/_BR005.md
> +ovalidity of the code of the Customs office of import
"ovalidity" typo

2023-09-06 09:15 UTC, ChrisCookOC commented on source/documentation/partials/_BR009.md
> +othe transport mode is either sea or inland waterway
"othe" typo

2023-09-06 09:21 UTC, ChrisCookOC commented on source/documentation/partials/_BR010.md
> +othe consignor is allowed to leave these fields empty
"othe" typo

2023-09-06 09:21 UTC, ChrisCookOC commented on source/documentation/partials/_BR011.md
> +onature of goods compared to the categories and/or products allowed for the consignee;
"onature" typo

2023-09-06 09:21 UTC, ChrisCookOC commented on source/documentation/partials/_BR011.md
> +onature of goods compared to the categories and/or products allowed for the consignee.
"onature" typo

2023-09-06 09:21 UTC, ChrisCookOC commented on source/documentation/partials/_BR012.md
> +ovalidity of the link (manages or uses) between (new) consignee and (new) place of delivery
"ovalidity" typo

2023-09-06 09:21 UTC, ChrisCookOC commented on source/documentation/partials/_BR017.md
> +o validity of the Customs office of export
random o again

2023-09-06 09:21 UTC, ChrisCookOC commented on source/documentation/partials/_BR014.md
> +o the (new) consignee is allowed to practise direct delivery
random o

2023-09-06 09:21 UTC, ChrisCookOC commented on source/documentation/partials/_BR027.md
> +othe code of the Excise office is mentioned in the temporary authorisation
"othe"

2023-09-06 09:21 UTC, ChrisCookOC commented on source/documentation/partials/_BR031.md
> +onature of goods compared to the categories allowed for splitting (energy products);
"onature"

2023-09-06 09:21 UTC, ChrisCookOC commented on source/documentation/partials/_BR031.md
> +oif destination data are left empty (Article 22 - at most once for the submission), the goods are subject to splitting according to the applicable common system parameter
"oif"

2023-09-06 09:21 UTC, ChrisCookOC commented on source/documentation/partials/_BR032.md
> +ono product has been added in any of the new e-Ads
"ono"

2023-09-06 09:21 UTC, ChrisCookOC commented on source/documentation/partials/_BR034.md
> +othe former e-AD had an empty destination
"othe"

2023-09-06 09:21 UTC, ChrisCookOC commented on source/documentation/partials/_BR048.md
> +onature of goods is the same compared to the categories and/or products allowed for the consignee;
"onature"

2023-09-06 09:25 UTC, mpbostock commented
I wonder if all these "typos" that Chris is finding is a flaw of the Python extraction from the DDNEA?? I know that CTC had to get the whole team to jump on and go through the extracted DDNTA and make sure the extracted pages made sense and were human readable. We will have to clean this up generally I think but is a good starting point at least. We also need to make sure that we don't have any rules/constraints etc. left over from the CTC copy as that would definitely be very confusing! 😂

2023-09-06 09:27 UTC, ChrisCookOC commented
@mpbostock  yeah it looks like it only happens on certain types of lines so its a conversion thing I'm sure!

2023-09-06 10:51 UTC, mauro-fanton commented
> Generally we have used excise-movement-control-system-tis in a few places instead of excise-movement-control-system-api-tis. Is this intentional / does it matter?

yes I agree. We might can rename it.

2023-09-06 11:01 UTC, mauro-fanton commented
yes, probably there is a problem with the python script. Yes we would need be careful with this as it has been a copy and paste job  as we did not know what info we needed. I think it will require every body efors, and specially James to see if we have the right info.

2023-09-06 11:19 UTC, crystalmark commented
Slopey shoulders...  all typos have been auto-imported from the DDNEA :-)

2023-09-11 10:25 UTC, mpbostock approved these changes

2023-09-11 11:20 UTC, merged