Added EMCS messages. Also removed some other messages that are not par…
hmrc/excise-movement-control-system-api-tis pull request #5
Opened 2023-10-24 10:59 UTC by mauro-fanton

…t of this delivery

2023-10-25 08:27 UTC, mpbostock requested changes
Can the messages.py be run and the new files added please? IE815 is still missing for example

2023-10-25 08:27 UTC, mpbostock commented on source/documentation/partials/_IE906.md
Can we remove this file? It's not in the list of IE messages we need to know about

2023-10-25 08:27 UTC, mpbostock commented on source/documentation/partials/_IE917.md
Can we remove this file? It's not in the list of IE messages we need to know about

2023-10-25 08:27 UTC, mpbostock commented on source/documentation/partials/_IE928.md
Can we remove this file? It's not in the list of IE messages we need to know about

2023-10-25 08:27 UTC, mpbostock commented on python/__pycache__/messages.cpython-38.pyc
We should probably remove this file and add something to the gitignore to ignore anything in a __pycache__ folder??

2023-10-25 08:27 UTC, mpbostock commented on python/__pycache__/utils.cpython-38.pyc
We should probably remove this file and add something to the gitignore to ignore anything in a __pycache__ folder??

2023-10-25 08:42 UTC, mauro-fanton commented on source/documentation/partials/_IE917.md
cannot see this in the PR. should have been removed.

2023-10-25 08:42 UTC, mauro-fanton commented on source/documentation/partials/_IE928.md
cannot see this in the PR. should have been removed.

2023-10-25 08:43 UTC, mauro-fanton commented
forgot to add , commit and push he IE815

2023-10-25 08:46 UTC, mauro-fanton commented
The me messages.py get run as part of messagetypes.py

2023-10-25 10:48 UTC, jlid87 commented on python/messagetypes.py
Can we add IE717, IE880?

2023-10-25 16:30 UTC, mpbostock submitted a review, later dismissed

2023-10-26 07:41 UTC, mpbostock approved these changes

2023-10-26 07:41 UTC, merged